import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body style={{ margin: 0, display: 'flex', flexDirection: 'column', height: '100vh' }}>
        
        {/* --- サイト全体の共通ヘッダー --- */}
        <header style={{
          height: '60px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center', // これで中身を水平中央に寄せます
          padding: '0 2rem',
          backgroundColor: '#fff',
          borderBottom: '1px solid #e5e7eb',
          position: 'relative',    // 左右に何か置きたくなった時のための基準
          zIndex: 1000,
        }}>
          <h1 style={{ 
            fontSize: '1.4rem', 
            margin: 0, 
            color: '#2d5a27', 
            fontFamily: 'serif',
            letterSpacing: '0.15em',
            fontWeight: 'bold',
          }}>
            GARDEN MEISTER
          </h1>
        </header>

        {/* --- ここに各ページ（GardenSceneなど）が入る --- */}
        <main style={{ flex: 1, position: 'relative', overflow: 'hidden' }}>
          {children}
        </main>

      </body>
    </html>
  );
}
