import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Garden Meister | チューリップの庭を作るゲーム",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="min-h-screen">

        {/* --- ここに各ページ（GardenSceneなど）が入る --- */}
        <main style={{ flex: 1, position: 'relative', overflow: 'hidden' }}>
          {children}
        </main>

      </body>
    </html>
  );
}
